# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/java_etl_grpc_client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$src/proto/java_etl_grpc_client.proto\"\x16\n\x14NotParametersRequest\"w\n\x13Oauth2TokenResponse\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12\x14\n\x0crefreshToken\x18\x02 \x01(\t\x12\x11\n\texpiresIn\x18\x03 \x01(\x05\x12\x0e\n\x06scopes\x18\x04 \x01(\t\x12\x12\n\nclientName\x18\x05 \x01(\t\"h\n\x13RefreshTokenRequest\x12\x14\n\x0crefreshToken\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x02 \x01(\t\x12\x10\n\x08\x63lientId\x18\x03 \x01(\t\x12\x14\n\x0c\x63lientSecret\x18\x04 \x01(\t2\x8b\x01\n\rOauth2Service\x12<\n\x0bloginClient\x12\x15.NotParametersRequest\x1a\x14.Oauth2TokenResponse\"\x00\x12<\n\x0crefreshToken\x12\x14.RefreshTokenRequest\x1a\x14.Oauth2TokenResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.java_etl_grpc_client_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTPARAMETERSREQUEST._serialized_start=40
  _NOTPARAMETERSREQUEST._serialized_end=62
  _OAUTH2TOKENRESPONSE._serialized_start=64
  _OAUTH2TOKENRESPONSE._serialized_end=183
  _REFRESHTOKENREQUEST._serialized_start=185
  _REFRESHTOKENREQUEST._serialized_end=289
  _OAUTH2SERVICE._serialized_start=292
  _OAUTH2SERVICE._serialized_end=431
# @@protoc_insertion_point(module_scope)
